#! /usr/bin/env bash
#
# Copyright (c) 2019-2020, Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

#
# This script builds the TF in different configs.
# Rather than telling cov-build to build TF using a simple 'make all' command,
# the goal here is to combine several build flags to analyse more of our source
# code in a single 'build'. The Coverity Scan service does not have the notion
# of separate types of build - there is just one linear sequence of builds in
# the project history.
#

# Bail out as soon as an error is encountered.
set -e

tf_coverity_dir="$(readlink -f "$(dirname "$0")/")"
base_dir="$(readlink -f "$(dirname "$0")/../../../")"

. $tf_coverity_dir/common-def.sh

# a single makefile takes care of all platform building
make BASE_DIR="$base_dir" -f "$tf_coverity_dir/cov-makefile"
